### ISSUE TITLE
搜索功能无法使用

### ISSUE THREAD

**Issue by pokalo81124** [amzrk2/hugo-theme-fuji#107]
您好，今天发现搜索功能突然无法正常使用了，看了一下demo也出现了同样的问题，想问一下如何解决。

**Comment by andrew-aiken** [comment]
Noticed the same issue.
If I find a solution I'll let you know

**Comment by andrew-aiken** [comment]
@pokalo81124 Found the issue!

The art-template script was causing issues. I switched out [this line](https://github.com/dsrkafuu/hugo-theme-fuji/blob/16c4b8d301e0a81aa29e3c36fc7cd9ff4096d9ff/layouts/partials/scripts-end.html#L2)

With the following

```js
<script defer src="https://cdn.jsdelivr.net/npm/art-template@4.13.2/lib/template-web.js" integrity="sha256-5giHTB6g18PZS8ficjELg/n/f6asTMCLp7I0xKrZ6xk=" crossorigin="anonymous"></script>
```

I'll open a PR for the fix

**Comment by pokalo81124** [comment]
> @pokalo81124 Found the issue!
> 
> The art-template script was causing issues. I switched out [this line](https://github.com/dsrkafuu/hugo-theme-fuji/blob/16c4b8d301e0a81aa29e3c36fc7cd9ff4096d9ff/layouts/partials/scripts-end.html#L2)
> 
> With the following
> 
> ```js
> <script defer src="https://cdn.jsdelivr.net/npm/art-template@4.13.2/lib/template-web.js" integrity="sha256-5giHTB6g18PZS8ficjELg/n/f6asTMCLp7I0xKrZ6xk=" crossorigin="anonymous"></script>
> ```
> 
> I'll open a PR for the fix

抱歉现在才看到！！！！！！谢谢您的解决方案，thank you very much！！！！

**Comment by pokalo81124** [comment]
> @pokalo81124 Found the issue!
> 
> The art-template script was causing issues. I switched out [this line](https://github.com/dsrkafuu/hugo-theme-fuji/blob/16c4b8d301e0a81aa29e3c36fc7cd9ff4096d9ff/layouts/partials/scripts-end.html#L2)
> 
> With the following
> 
> ```js
> <script defer src="https://cdn.jsdelivr.net/npm/art-template@4.13.2/lib/template-web.js" integrity="sha256-5giHTB6g18PZS8ficjELg/n/f6asTMCLp7I0xKrZ6xk=" crossorigin="anonymous"></script>
> ```
> 
> I'll open a PR for the fix

抱歉现在才看到！！！！！！谢谢您的解决方案，thank you very much！！！！
