### ISSUE TITLE
How to change the background colour and font?

### ISSUE THREAD

**Issue by iamharshkumar97** [amzrk2/hugo-theme-fuji#11]
Where can I find the setting to change these?

Thanks

**Comment by dsrkafuu** [comment]
For now there's no ready-made way to change the background color. But actually, all the scss code put in the `custom.scss` will be generated into site's main css, background colour can alse be defined through this way.

As for font, you can change the font size/color, font-family and theme color scheme also using custom scss, check more details at https://github.com/amzrk2/hugo-theme-fuji#advance-configration.

**Comment by iamharshkumar97** [comment]
Thank you for the reply. 
So which file should I copy from the theme folder to make changes and then save it as `custom.scss`?
Also can I save my custom font in assets folder and then reference it in `custom.scss` ?

**Comment by dsrkafuu** [comment]
Just create a new `sitefolder/assets/sass/custom.scss` and copy variables you want to change from readme.

Need Hugo extended version.

Font-face works, if your custom font is `sitefolder/static/fonts/aaa.woff2`:

```
@font-face {
    ...
    url(/fonts/aaa.woff2)
}
```

Then change the `font-family`.

**Comment by iamharshkumar97** [comment]
Thank you for all the help.
Final question. Sorry for my ignorance but what should I add in `custom.scss `for background?

Reference: 

>  background colour can alse be defined through this way.


Also I tried changing the font. It didn't work.
```
@font-face {
    font-family: 'mallory';
    src: url(/fonts/mallory.woff2);
}
```

I added this.

**Comment by dsrkafuu** [comment]
For example:
```
body {
    background-color: #3F3F3F !important;
}
```

About font, see: https://imgur.com/a/JJ64ic5
