### ISSUE TITLE
How to set up Google Analytics tracking ID

### ISSUE THREAD

**Issue by ress997** [amzrk2/hugo-theme-fuji#2]
hugo uses `.Site.GoogleAnalytics` by default.
https://gohugo.io/templates/internal/#google-analytics

But you're supposed to use `.Site.Params.GoogleAnalyticsUA`, is that what you intended to do?

**Comment by amzrk2** [comment]
@ress997 
Generally I just use global gtag.js out of habit, actually for now it's basically same as Hugo's internal analytics.js. So I'm using the [```layouts/partials/analytic-google.html```](https://github.com/amzrk2/hugo-theme-fuji/blob/master/layouts/partials/analytic-google.html). You can find out their inner difference at https://stackoverflow.com/questions/23640645/what-is-the-difference-between-google-tag-manager-and-google-analytics .

**Comment by ress997** [comment]
I think it would be better to change the variable from ".Site.Params.GoogleAnalyticsUA" to ".Site.GoogleAnalytics" if you're using the same code internally.
I think the changes will make it easier to transition from other themes.

**Comment by amzrk2** [comment]
Done. Commited to dev branch at https://github.com/amzrk2/hugo-theme-fuji/commit/a2d3c7aa1e284f141e14481523f3488a65ccdbd7 .

**Comment by ress997** [comment]
Thank you
