### ISSUE TITLE
disqus

### ISSUE THREAD

**Issue by xenoterracide** [amzrk2/hugo-theme-fuji#22]
does this theme support disqus, ever since I migrated my blog, (which included moving hosts and updating the theme) my disqus hasn't worked. As far as I can tell I've done all the migration steps on disqus, but it's still not showing up.

https://xenoterracide.com
https://github.com/xenoterracide/blog

**Comment by xenoterracide** [comment]
it was my baseurl

**Comment by dsrkafuu** [comment]
Thanks for using the theme. 😊

If you're interested in v2 version of the theme please check dev branch, or preview it at https://blog.amzrk2.cc
Note that v2 is still under development, there may be major changes.
