### ISSUE TITLE
Can noLicense be true by default?

### ISSUE THREAD

**Issue by nicholaskajoh** [amzrk2/hugo-theme-fuji#23]
Hi @amzrk2,

Thanks for making this theme.

Can `noLicense` be `true` by default? Personally, I think having a copyright notice in the footer should suffice. Having to put `noLicense = true` on all my posts (over 40) is unnecessary and a lot of work.

Cheers!

**Comment by dsrkafuu** [comment]
@nicholaskajoh 
Thanks for using the theme!
I will make this option (`noLicense = true`) available in global `config.toml` in Fuji-v2 which will be released after a few days (before this weekend).
You can check out [this issue #21](https://github.com/amzrk2/hugo-theme-fuji/issues/21) or the `dev` branch for development progress.
