### ISSUE TITLE
关于搜索的建议

### ISSUE THREAD

**Issue by Briy09** [amzrk2/hugo-theme-fuji#26]
- use lunr.js
https://koirand.github.io/blog/ ,search "vim" for example.
https://github.com/koirand/pulp
或者 [hugo-lunr-zh](https://www.npmjs.com/package/hugo-lunr-zh)，看哪个好。
- use Fuse.js
https://gist.github.com/cmod/5410eae147e4318164258742dd053993

其他 https://gohugo.io/tools/search/

下面的例子虽然是jekyll的，但也是静态博客，相关原理应该差不多吧。效果如下：
https://simpleyyt.com/ ,search "is" for example.
https://github.com/simpleyyt/jekyll-theme-next

https://blog.tmaize.net/pages/search.html ,search "ssh" for example.
https://github.com/TMaize/tmaize-blog

**Comment by amzrk2** [comment]
@Briy09 
感谢建议，正在研究 Fuse.js，有空应该会加上🧐
