### ISSUE TITLE
主页不显示帖子

### ISSUE THREAD

**Issue by chenshenwei1998** [amzrk2/hugo-theme-fuji#27]
作者您好，我想问一下为什么我用了examplesite里面的配置文件以后主页上不显示post了而是一片空白了，谢谢

**Comment by dsrkafuu** [comment]
刚刚测试无问题，示例的配置文件规定的 md 文件是要放到 content/post，可以在里面修改 main section，对应你文件的位置
![20200606232951.png](https://i.loli.net/2020/06/06/P1VUWh7LDKuojsB.png)
![20200606233006.png](https://i.loli.net/2020/06/06/LdwCWxzEiB7kf1s.png)

**Comment by chenshenwei1998** [comment]
我发现是文件夹名字的问题，非常感谢！
