### ISSUE TITLE
Dark theme darkens images - how to disable?

### ISSUE THREAD

**Issue by willhsieh** [amzrk2/hugo-theme-fuji#31]
When using dark mode, all images are darkened. How do I turn this off?

Example (scroll all the way down): https://willhsieh.com/posts/how-precise-do-numbers-have-to-be/

**Comment by dsrkafuu** [comment]
@limelego 
Darken image is an old style that was ported from v1.
It will become optional in `config.toml` after the next release a few days later with a new search feature.

You can still disable it now by using Hugo Extended and modifying the scss file, but the process is a little more complicated.
