### ISSUE TITLE
image shortcodes missing

### ISSUE THREAD

**Issue by theapiarist** [amzrk2/hugo-theme-fuji#37]
../Fuji/layouts/shortcodes only contains img-lazy.html ... docs indicate there should be i**mg-nz** and **img-nz-lazy** as well. Using these shortcodes causes a build error:

```
/blah/blah/01/triffids.md:27:1": failed to extract shortcode: template for shortcode "img-nz-lazy" not found

25 26 27 28 | {{< img-nz-lazy "Alt text" "/Screenshot-2019-01-12-17.11.54.png" >}}

Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown
```

This may be my inexperience with Hugo and shortcodes ...

**Comment by dsrkafuu** [comment]
Oh, it was my fault.
The zoomable image depends on medium-zoom which once had some compatibility issues with the dark mode.
So the codes for medium-zoom were removed at that time.
I have fixed it but forgot to bring the zoomable image back in so I'll make it work in the next few days. 😂

**Comment by theapiarist** [comment]
With thanks. I’ll look forward to it.
Thanks for your work on the theme.
D.

**Comment by dsrkafuu** [comment]
Shortcodes should now work correctly🧐
Try update the theme
