### ISSUE TITLE
Search using baseURL with subpage results into index.json not found

### ISSUE THREAD

**Issue by rrtjr** [amzrk2/hugo-theme-fuji#38]
Hello, 

I just want to ask if there's a workaround for the search function given that my base URL has a subpage? 

With a base URL of http://localhost:1313/brain-dump/ for example, index.json is being searched on the root level (http://localhost:1313/). 

![image](https://user-images.githubusercontent.com/200704/88348997-74117d80-cd81-11ea-9805-466a054ac998.png)

It exists however when accessed using the complete base URL. 

![image](https://user-images.githubusercontent.com/200704/88349050-9905f080-cd81-11ea-9a41-fa42231be3b4.png)

Is there a way where I can override the index.json file path?

https://github.com/amzrk2/hugo-theme-fuji/blob/007f3ba1c9a9a80a13156bd148cc4ad87af8c5a9/assets/js/fuji.js#L133 

I'm not really sure if this is purely a config issue on my part. Your insight would be very helpful. Thanks!

**Comment by dsrkafuu** [comment]
Thanks for your issue.
I have fixed the relative link issue just now 😁

Check out this release for more details about how to fix it: https://github.com/amzrk2/hugo-theme-fuji/releases/tag/v2.2.0

**Comment by rrtjr** [comment]
Hello, seems fixed on my end. Thanks!

**Comment by danielhollas** [comment]
@amzrk2 I just stumbled on this issue of search as well. It would be nice to add info to `README.md` about how to setup search (or at least least point people to `exampleSite/config.toml` where they can see the full example config. Before I saw it, it was not clear to me e.g. how to setup the menus etc.) (I'm new to Hugo)

Great work btw, loving this theme!

**Comment by dsrkafuu** [comment]
> 
> 
> @amzrk2 I just stumbled on this issue of search as well. It would be nice to add info to `README.md` about how to setup search (or at least least point people to `exampleSite/config.toml` where they can see the full example config. Before I saw it, it was not clear to me e.g. how to setup the menus etc.) (I'm new to Hugo)
> 
> Great work btw, loving this theme!

@danielhollas I tried to add some information about the config files in the README: https://github.com/amzrk2/hugo-theme-fuji/blob/master/README.md#-getting-started
