### ISSUE TITLE
Sidebar in mobile version

### ISSUE THREAD

**Issue by FelixBenning** [amzrk2/hugo-theme-fuji#45]
![grafik](https://user-images.githubusercontent.com/29106652/94830122-8526dc80-040b-11eb-9c45-e4ea625f76ca.png)

I played with the size in F12 a little and the sidebar does something weird when it drops below the content

**Comment by FelixBenning** [comment]
the menus are also difficult to find down there - a hamburger menu might be nice? I don't know. I am not really a front end developer so I am currently trying to find a theme I do not have to adjust at all 😅. That proves to be quite difficult.

**Comment by dsrkafuu** [comment]
This is a "failed" design inherited from an earlier development and should be replaced with a pop-up overlay and a button in the bottom right corner in the near future. 😂

**Comment by dsrkafuu** [comment]
New sidebar added by @rexarski in #47

**Comment by FelixBenning** [comment]
awesome!
