### ISSUE TITLE
Emphasis vs Link color

### ISSUE THREAD

**Issue by FelixBenning** [amzrk2/hugo-theme-fuji#51]
I noticed that you are using the same color for links and emphasis. It is a little confusing to have some things with that color be clickable and other things which are not. Especially since "emphasised and clickable" is probably exactly the same as "only emphasised".

![grafik](https://user-images.githubusercontent.com/29106652/95011426-e976b580-0630-11eb-8078-ca5f4dff3a6e.png)

Not a huge issue of course

**Comment by dsrkafuu** [comment]
I'm considering whether or not to add an underline to the links, not sure if it will affect the overall feel of it.

**Comment by FelixBenning** [comment]
given how few websites use underlines for links nowadays I suspect that "it doesn't look good". But given that I am not a designer I don't know if a different color would be better or whether that would make the color palette to excited. You could of course remove the color entirely and let *cursive* speak for itself. 

But given that you actually created a theme which "looks good" without knowing really why, I would trust your instinct better than mine.

**Comment by jiedxu** [comment]
I like having more coloured text, but there are already many links in my posts. Some reader might think non-clickable words are dead links. I made the following change:

![Screenshot 2021-03-15 at 07 13 43](https://user-images.githubusercontent.com/19307850/111111105-04454280-855e-11eb-89ef-7d16d06e5187.png)

**Comment by retrhelo** [comment]
I suggest not using any color for emphasis, like github and many other editors do. The _italic_ font itself is the best way to "emphasis" the text.

The change can be easily done by removing codes in `assets/scss/_fuji-theme/_style.scss`.

```scss
strong,
em {
  color: var(--color-secondary);
}
```

**Comment by dsrkafuu** [comment]
Modded in 253850bb1f3b0faae8472f31a28725fec8684ffa
