### ISSUE TITLE
[bug] TOC not shown

### ISSUE THREAD

**Issue by choicky** [amzrk2/hugo-theme-fuji#55]
侧面未显示目录，不知道原因是什么。

即使配置文件或者页面本身设定了 `showToc = true` 也不显示

**Comment by dsrkafuu** [comment]
目录默认设置的显示层级是二级到三级，也就是 `##` 到 `###`

**Comment by alexmitelman** [comment]
Hi TOC is not shown for me too.

test.md
```
---
title: "Test TOC"
date: 2020-10-18T14:35:48+03:00
draft: false
---


# Level 1

## Level 2

### Level 3
```

config.toml
```
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
```
![Screenshot_2020-10-18 Test TOC](https://user-images.githubusercontent.com/26745241/96378189-05329d80-1193-11eb-9c19-3a0e32b9b406.png)

**Comment by dsrkafuu** [comment]
I've tried modifying the TOC display logic, and now it should show the TOC in all cases unless it is explicitly set `false` within `config.toml` or front matter.
Also, previously TOC would only be displayed on pages belonging to the `mainSection` array set in `config.toml`.
I've tested well with the `exampleSite`, try updating the theme.

I'll keep the issue open until all problems are fixed.

**Comment by dsrkafuu** [comment]
As #61 mentioned, this may actually a bug where `showToc=true` is not working as expected. I've fixed it in the latest commit, you can upgrade the theme and try again with `showToc=false` in global and `showToc=true` in front matters.

The right logic:
|     fixed setting status      | site `showToc` is `undefined` or `true` | site `showToc` is `false` |
| :---------------------------: | :-------------------------------------: | :-----------------------: |
| page `showToc` is `undefined` |                   ✅                    |            ❎             |
|   page `showToc` is `true`    |                   ✅                    |            ✅             |
|   page `showToc` is `false`   |                   ❎                    |            ❎             |
