### ISSUE TITLE
index page misses formatting when you don't use `<!--more-->`

### ISSUE THREAD

**Issue by emilburzo** [amzrk2/hugo-theme-fuji#56]
Hi,

First off, amazing theme, I especially love the built-in dark mode :heart: 

I'm new to hugo, so I'm not sure if the bug is in this theme or in hugo itself, but:

If I don't use `<!--more-->` in my posts, the index page is missing all the formatting, it's just raw text, e.g.:

# Without `<!--more-->`

![image](https://user-images.githubusercontent.com/6228327/96501165-a46d9880-1258-11eb-86a6-b5271c1e7b57.png)

# With `<!--more-->`

![image](https://user-images.githubusercontent.com/6228327/96501197-b3ece180-1258-11eb-9be0-bad0fb9d96fb.png)

This only happens for the index page, the actual post page itself is fine in both cases.

Thanks!

**Comment by dsrkafuu** [comment]
That's actually how Hugo works. 

By adding the `<!--more-->` to specify summary part, Hugo will pass rendered HTML to `{{ .Summary }}`, otherwise its just raw text cut from files according to summary length settings.

**Comment by emilburzo** [comment]
Huh, that's pretty strange behavior...

Thanks for the information and sorry for the noise!
