### ISSUE TITLE
og image cannot be replaced.

### ISSUE THREAD

**Issue by rexarski** [amzrk2/hugo-theme-fuji#63]
I followed the instruction in README to replace the open graph variable with my own og.png. Now the image be accessed through [https://qrui.xyz/img/og.png](https://qrui.xyz/img/og.png), but whenever I share my link within Telegram, it still appear to be the one from the theme.

<img width="479" alt="iShot2020-12-27 15 34 40" src="https://user-images.githubusercontent.com/4172477/103163965-25e53680-4859-11eb-9732-118956e33cf4.png">

**Comment by dsrkafuu** [comment]
The preview from Facebook Debugger shows the right og image: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fqrui.xyz

So it is possible that the old images were cached by telegram when sharing the site before the og images were replaced. You can try to change the file name and the corresponding link like `_opengraph.[ext]`, in any case, it should be a telegram problem.

However, the best practice for og images is to use absolute urls, so I have made a fix, please refer to [this release v2.5.0](https://github.com/amzrk2/hugo-theme-fuji/releases/tag/v2.5.0) to update the theme and maybe fix the issue.

**Comment by rexarski** [comment]
Thank you!
