### ISSUE TITLE
Must build with minimum hugo v0.74.0

### ISSUE THREAD

**Issue by jiedxu** [amzrk2/hugo-theme-fuji#64]
Thanks for the wonderful theme. 

However, I cannot render it on my computer. For example, the message for page "home" is:

```
ERROR 2021/01/03 20:44:00 render of "home" failed: execute of template failed: template: _default/list.html:24:7: executing "_default/list.html" at <partial "scripts-end.html" .>: error calling partial: "/Users/edxu96/GitHub/edxu96.github.io/themes/fuji-modified/layouts/partials/scripts-end.html:10:42": execute of template failed: template: partials/scripts-end.html:10:42: executing "partials/scripts-end.html" at <js>: can't evaluate field Build in type string
```

I delete line [10 and 11](https://github.com/amzrk2/hugo-theme-fuji/blob/1500c3c475e0ff99e6693dd11118e1a937b9ff34/layouts/partials/scripts-end.html#L10), which seem to call `fuji.js`, then the two buttons in the corner don't work. Also, the function for tags doesn't work.

My implementation is hosted in https://github.com/edxu96/edxu96.github.io . The version of `hugo` on my mac is:

```
Hugo Static Site Generator v0.69.2-EC9DCF30/extended darwin/amd64 BuildDate: 2020-04-24T07:55:42Z
```

Could you please share some hints?

**Comment by dsrkafuu** [comment]
@edxu96 
The theme switched from using the gulp workflow to using hugo's built-in esbuild to compile JavaScript code a while ago, so the minimum Hugo version required is [0.74.0 released at 13 Jul 2020](https://github.com/gohugoio/hugo/releases/tag/v0.74.0).

**Comment by jiedxu** [comment]
Thanks for the quick reply. It works now.

I did run `brew upgrade hugo`, but there was something wrong with my `homebrew`. Should have double-checked.
