### ISSUE TITLE
[Feature Request] Position APlayer in body of post

### ISSUE THREAD

**Issue by asbrwl** [amzrk2/hugo-theme-fuji#66]
Could there be a way to embed the APlayer in the body of the post rather than immediately after the post Title and Meta?

**Comment by dsrkafuu** [comment]
@akhileshsabharwal 

Currently the player can only be attached immediately after the post title and meta, but its easy to add a shortcode to make players available in post content.

I will be finishing this feature soon.

**Comment by dsrkafuu** [comment]
Hello @akhileshsabharwal ,
the in-post APlayer support has been released in [v2.6.0](https://github.com/amzrk2/hugo-theme-fuji/releases/tag/v2.6.0).

**Comment by asbrwl** [comment]
Awesome!
