### ISSUE TITLE
no permissions to add language file

### ISSUE THREAD

**Issue by 1000283** [amzrk2/hugo-theme-fuji#75]
Trying to add esperanto translation to i18n/eo.toml, no permissions.
Can't add via web interface either.
Attached `eo.toml` **renamed to txt** 'cos `.toml` isn't accepted.
[eo.txt](https://github.com/dsrkafuu/hugo-theme-fuji/files/6290073/eo.txt)

**Comment by dsrkafuu** [comment]
Added in 17629987d294e8dd9afae5ec6317a20550e3bd17
