### ISSUE TITLE
Default to dark mode

### ISSUE THREAD

**Issue by 12nick12** [amzrk2/hugo-theme-fuji#79]
I would love a way to default to dark mode. Other than that, thank you this is a nice simple theme.

**Comment by dsrkafuu** [comment]
The default theme is automatically detected by your system.

For example, when using dark mode in the new Microsoft Edge or using Safari with system dark mode on macOS, the theme will choose dark mode when you first enter it.

**Comment by 12nick12** [comment]
OK, so there's no way to force it?

**Comment by dsrkafuu** [comment]
I added this feature in v2.7.0.
https://github.com/dsrkafuu/hugo-theme-fuji/blob/8151cf402bbd3bb6ba33fa78894d8f6d5aecd157/exampleSite/config.toml#L33-L36

**Comment by 12nick12** [comment]
Awesome, thank you so much.
