### ISSUE TITLE
Changing colors

### ISSUE THREAD

**Issue by mettix** [amzrk2/hugo-theme-fuji#8]
Hi,

I'm fairly new to Hugo, I've been able to install Hugo, make content, install the theme.

But i'm trying to change the color scheme.

I found out that the base color is defined in;

`themes\fuji\assets\sass\_var.scss` 

But changing it there does not work. 

I also found this; but that is a generated file, I don't want to change it there.

`grep -rl "#8AA2D3" * .*
resources/_gen/assets/scss/sass/main.scss_c266f84bc22ee05ee0ecdfd29660f0aa.content`

What is the correct way to change the color scheme? 
My goal is to re-use my website theme (bootstrap). But knowing where the add CSS is a crucial step for that : ))

**Comment by dsrkafuu** [comment]
@mettix

Only **extended** version of Hugo can build css from scss, so if you use the normal version, it will directly use the pre-built resources in `resources/_gen` folder.
If you want to apply the modified scss, you need to use extended version, you can find it at Hugo's release page.

Also, you can use `SITEROOTFOLDER/assets/sass/_var.scss` to **cover** the scss in `SITEROOTFOLDER/themes/fuji/assets/sass/_var.scss`, just copy it out for modification. This can help keep the theme folder's git worktree clean which makes future update easier.

**Comment by dsrkafuu** [comment]
New `custom.scss` will be added in future for easy modification of theme's color scheme, font stack and so on.

**Comment by mettix** [comment]
Hi amzrk2,

Thanks for the feedback! Looking forward to it :)
