### ISSUE TITLE
Considering support `$ ... $` as inline math 

### ISSUE THREAD

**Issue by Origami404** [amzrk2/hugo-theme-fuji#89]
Hello. I'm really impressed by your awesome theme and I decide use it as my blog theme. But it seems like the theme doesn't support using `$ ... $` as inline math. I think this notation is quite popular and it will be awesome to have it supported. 

Anyway, thanks you for creating such a beautiful theme.

**Comment by dsrkafuu** [comment]
```js
[
  { left: "$$", right: "$$", display: true },
  { left: "\\[", right: "\\]", display: true },
  { left: "$", right: "$", display: false },
  { left: "\\(", right: "\\)", display: false },
]
```

Supported in v2.8.2.
